name: test
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone Google test
        run: git clone https://github.com/google/googletest.git -b release 1.11.0
      - name: Configure CMake
        run: cmake -S. -Bbuild
      - name: Build
        run: cmake --build build
      - name: Run Tests
        run: ctest --test-dir build --output-on-failure